#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bump_version () {
  message="$(cat $1)"
  required="^(\[publish\]) .*$"

  # Whenever you add `[publish]` tag inside git commit, the package version will be bumped
  if ! [[ $message =~ $required ]]; then
    npx bump patch && git add .
  fi
}

npx lint-staged